[tool.aerich]
tortoise_orm = "bot.services.database.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.poetry]
name = "base-tg-bot"
version = "1.0.0"
description = ""
authors = ["TrixiS <oficialmorozov@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "base_tg_bot"}]

[tool.poetry.dependencies]
python = "^3.10"
aiogram3-form = "^0.1.2"
tortoise-orm = "^0.19.2"
pydantic = {extras = ["dotenv"], version = "^1.10.4"}
aioschedule = "^0.5.2"
aiogram = {git = "https://github.com/aiogram/aiogram.git", rev = "fad45c66aa7833eab8c60d87cb2567c4012de655"}
aerich = "^0.7.1"

[tool.poetry.group.dev.dependencies]
typer = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
