[tool.poetry]
name = "base-tg-bot"
version = "1.0.0"
description = ""
authors = ["TrixiS <oficialmorozov@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = {extras = ["dotenv"], version = "^1.10.7"}
aioschedule = "0.5.2"
aiogram = {git = "https://github.com/aiogram/aiogram.git", rev = "cf269e15f4a098b051f97bc68bb2e710d3d61d8a"}
typer = "0.7.0"
aiogram3-form = "0.3.3"
tortoise-orm = "^0.19.3"
aerich = "^0.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
